export const GET_PANTRY_ITEMS = 'GET_PANTRY_ITEMS';
export const ADD_PANTRY_ITEM = 'ADD_PANTRY_ITEM';
export const DELETE_PANTRY_ITEM = 'DELETE_PANTRY_ITEM';
export const UPDATE_PANTRY_ITEM = 'UPDATE_PANTRY_ITEM';
export const ITEMS_PANTRY_LOADING = 'ITEMS_PANTRY_LOADING';
export const SEARCH_PANTRY = 'SEARCH_PANTRY';

export const GET_FRIDGE_ITEMS = 'GET_FRIDGE_ITEMS';
export const ADD_FRIDGE_ITEM = 'ADD_FRIDGE_ITEM';
export const DELETE_FRIDGE_ITEM = 'DELETE_FRIDGE_ITEM';
export const UPDATE_FRIDGE_ITEM = 'UPDATE_FRIDGE_ITEM';
export const ITEMS_FRIDGE_LOADING = 'ITEMS_FRIDGE_LOADING';
export const SEARCH_FRIDGE = 'SEARCH_FRIDGE';

export const GET_FREEZER_ITEMS = 'GET_FREEZER_ITEMS';
export const ADD_FREEZER_ITEM = 'ADD_FREEZER_ITEM';
export const DELETE_FREEZER_ITEM = 'DELETE_FREEZER_ITEM';
export const UPDATE_FREEZER_ITEM = 'UPDATE_FREEZER_ITEM';
export const ITEMS_FREEZER_LOADING = 'ITEMS_FREEZER_LOADING';
export const SEARCH_FREEZER = 'SEARCH_FREEZER';

export const GET_GROCERY_ITEMS = 'GET_GROCERY_ITEMS';
export const ADD_GROCERY_ITEM = 'ADD_GROCERY_ITEM';
export const DELETE_GROCERY_ITEM = 'DELETE_GROCERY_ITEM';
export const UPDATE_GROCERY_ITEM = 'UPDATE_GROCERY_ITEM';
export const ITEMS_GROCERY_LOADING = 'ITEMS_GROCERY_LOADING';

export const GET_RECIPE_ITEMS = 'GET_RECIPE_ITEMS';
export const ADD_RECIPE_ITEM = 'ADD_RECIPE_ITEM';
export const DELETE_RECIPE_ITEM = 'DELETE_RECIPE_ITEM';
export const UPDATE_RECIPE_ITEM = 'UPDATE_RECIPE_ITEM';
export const ITEMS_RECIPE_LOADING = 'ITEMS_RECIPE_LOADING';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const FILTER_RECIPE_BY_TYPE = 'FILTER_RECIPE_BY_TYPE';
export const SORT_RECIPES = 'SORT_RECIPES';

export const GET_MEAL_PLANS = 'GET_MEAL_PLANS';
export const GET_MEAL_PLAN_BY_ID = 'GET_MEAL_PLAN_BY_ID';
export const ADD_MEAL_PLAN = 'ADD_MEAL_PLAN';
export const DELETE_MEAL_PLAN = 'DELETE_MEAL_PLAN';
export const UPDATE_MEAL_PLAN = 'UPDATE_MEAL_PLAN';
export const MEAL_PLAN_LOADING = 'MEAL_PLAN_LOADING';

